# .kodiak.toml
version = 1

[merge]
require_automerge_label = false
delete_branch_on_merge = true

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]

[update]
always = true # default: false
require_automerge_label = false # default: true
ignored_usernames = ["dependabot"]